### ISSUE TITLE
15.5已更新，但是cpu主频识别异常

### ISSUE THREAD

**Issue by skylark36** [isNextJuly/Hackintosh-EFI-for-deskmini-310-i7-8700#6]
![image](https://user-images.githubusercontent.com/19505695/82978336-e9c5cb00-a016-11ea-9a0a-b858848ee1e4.png)
![image](https://user-images.githubusercontent.com/19505695/82978346-f2b69c80-a016-11ea-9168-333fe56db54b.png)
不知道需要修改哪里，一重启一个样😂

**Comment by skylark36** [comment]
cpu型号 i5-8500

**Comment by isNextJuly** [comment]
> cpu型号 i5-8500

clover吗？试试 原生电源管理  选项  去除 看看

**Comment by skylark36** [comment]
> > cpu型号 i5-8500
> 
> clover吗？试试 原生电源管理 选项 去除 看看

已经换了一份efi了😂
